
OBJS = tokenizer.o history.o tester.o uimain.o

CFLAGS=-g -O3

all: uimain

tokenizer.o:history.h tokenizer.h

uimain: $(OBJS)
	cc -o uimain $(CFLAGS) $(OBJS)

clean:
	rm -f *.o uimain

run: unimain
	./uimain

